In [1]:
import pandas as pd

In [4]:
data = {
    '수학' : [90, 80],
    '영어' : [70, 60]
}

data2 = {
    '언어' : [20, 70],
    '과학' : [30, 60]
}

data3 = {
    '수학' : [100, 90],
    '영어' : [85, 65]
}

In [5]:
data = pd.DataFrame(data)
data2 = pd.DataFrame(data2)
data3 = pd.DataFrame(data3)

In [6]:
data

   수학  영어
0  90  70
1  80  60

In [7]:
data + data3

    수학   영어
0  190  155
1  170  125

In [8]:
pd.concat([data, data2], axis=0)

     수학    영어    언어    과학
0  90.0  70.0   NaN   NaN
1  80.0  60.0   NaN   NaN
0   NaN   NaN  20.0  30.0
1   NaN   NaN  70.0  60.0

In [10]:
pd.concat([data, data2], axis=1)

   수학  영어  언어  과학
0  90  70  20  30
1  80  60  70  60

In [11]:
data['언어'] = data2['언어']
data['과학'] = data2['과학']
data

   수학  영어  언어  과학
0  90  70  20  30
1  80  60  70  60

In [12]:
data[['언어', '과학']] = data2[['언어', '과학']]
data

   수학  영어  언어  과학
0  90  70  20  30
1  80  60  70  60

In [13]:
pd.concat([data, data3], axis=0)

    수학  영어    언어    과학
0   90  70  20.0  30.0
1   80  60  70.0  60.0
0  100  85   NaN   NaN
1   90  65   NaN   NaN